@baseURL = http://localhost:3000
@questionId = 1
@categoryIds = 1,2,3,4,5,6,7,8
# @categoryIds = 1,2
#Happy Path Testing

###
GET {{baseURL}}/health

###
GET {{baseURL}}/api/questions

###
GET {{baseURL}}/api/questions/{{questionId}}

###
GET {{baseURL}}/api/questions/random-categorized?categoryIds={{categoryIds}}

###
GET {{baseURL}}/api/questions/random

###
POST {{baseURL}}/api/generation/similar/{{questionId}}

###
POST {{baseURL}}/api/generation/followup/{{questionId}}

#Error Path Testing

###
# GET a question that does not exist -> 404
GET {{baseURL}}/api/questions/99999

###
# GET a question with an invalid ID format -> 400
GET {{baseURL}}/api/questions/abc

###
# get random categorized questions with invalid category IDs -> 400
GET {{baseURL}}/api/questions/random-categorized?categoryIds=invalid