name: CI Pipeline
on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:password@localhost:5432/riffbit_test
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: riffbit_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "24.11.0"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check Formatting
        run: npm run format

      - name: Push Schema to DB
        working-directory: ./server
        run: |
          npx prisma db push
          npx prisma db seed
        # ^ TODO: Refactor tests to set up data independently of seed script.
      - name: Test Server
        working-directory: ./server
        run: npx vitest run --reporter=verbose

      - name: Build Server
        working-directory: ./server
        run: npm run build

      - name: Test App
        working-directory: ./app
        run: npm test

      - name: Diagnose App
        working-directory: ./app
        run: npm run doctor
